[profile.default]
src = "src"
out = "out"
libs = ['node_modules', 'lib']
remappings = [
    '@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip',
    '@chainlink/contracts/=node_modules/@chainlink/contracts',
 ]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

solc_version = '0.8.26'
evm_version = "cancun"
optimizer_runs = 800
via_ir = false
ffi = true

[rpc_endpoints]
abitrumSepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
avalancheFuji = "${AVALANCHE_FUJI_RPC_URL}"